### ISSUE TITLE
Intermittent failure to send with SoftwareSerial

### ISSUE THREAD

**Issue by riban-bw** [FortySevenEffects/arduino_midi_library#9] opened 2014-03-03 09:13 UTC
Using SoftwareSerial, sendNoteOn() fails about every 4th attempt. Hardware (UART) serial works fine.

Simple test script which plays one note every second whilst button is pressed:

``` c++
#include <SoftwareSerial.h>
#include <MIDI.h>

USING_NAMESPACE_MIDI

SoftwareSerial softSerial(3,13);
MIDI_CREATE_INSTANCE(SoftwareSerial, softSerial, midiA);

static const unsigned int g_nSwitch = 7; //Press button to ground

void setup()
{
  pinMode(g_nSwitch, INPUT_PULLUP);
  midiA.begin(); //Initialise MIDI (serial) interface A
  midiA.sendProgramChange(0, 1);
  midiA.sendControlChange(AllNotesOff, 0, 1);
}

void loop()
{
  if(!digitalRead(g_nSwitch))
  {
    midiA.sendNoteOn(60, 127, 1);
    delay(500);
    midiA.sendNoteOff(60, 0, 1);
    delay(500);
  }
}
```

**Comment by Franky47** [comment] 2016-10-29 08:32
Cannot reproduce with Arduino 1.6.6 on a Leonardo board.

It seems odd that there would be interactions between the SoftSerial and MIDI library, as it only calls `begin` and `write` in this case, which has the same effect that writing it directly..

I'll close this for now, please let me know if you still have troubles with everything up to date.

**Closed by Franky47** 2016-10-29 08:32 UTC
Labels: bug
